<?php
function get_countries()
{
	return array(
		'Argentina' => __('Argentina', 'actify'),
		'Australia' => __('Australia', 'actify'),
		'Austria' => __('Austria', 'actify'),
		'Belarus' => __('Belarus', 'actify'),
		'Belgium' => __('Belgium', 'actify'),
		'Brazil' => __('Brazil', 'actify'),
		'Bulgaria' => __('Bulgaria', 'actify'),
		'Canada' => __('Canada', 'actify'),
		'Chile' => __('Chile', 'actify'),
		'China' => __('China', 'actify'),
		'Croatia' => __('Croatia', 'actify'),
		'Czech Republic' => __('Czech Republic', 'actify'),
		'Denmark' => __('Denmark', 'actify'),
		'Estonia' => __('Estonia', 'actify'),
		'Finland' => __('Finland', 'actify'),
		'France' => __('France', 'actify'),
		'Germany' => __('Germany', 'actify'),
		'Hong Kong' => __('Hong Kong', 'actify'),
		'Hungary' => __('Hungary', 'actify'),
		'India' => __('India', 'actify'),
		'Indonesia' => __('Indonesia', 'actify'),
		'Ireland' => __('Ireland', 'actify'),
		'Israel' => __('Israel', 'actify'),
		'Italy' => __('Italy', 'actify'),
		'Japan' => __('Japan', 'actify'),
		'Korea' => __('Korea', 'actify'),
		'Liechtenstein' => __('Liechtenstein', 'actify'),
		'Luxembourg' => __('Luxembourg', 'actify'),
		'Malaysia' => __('Malaysia', 'actify'),
		'Mexico' => __('Mexico', 'actify'),
		'Netherlands' => __('Netherlands', 'actify'),
		'New Zealand' => __('New Zealand', 'actify'),
		'Norway' => __('Norway', 'actify'),
		'Philippines' => __('Philippines', 'actify'),
		'Poland' => __('Poland', 'actify'),
		'Portugal' => __('Portugal', 'actify'),
		'Romania' => __('Romania', 'actify'),
		'Russia' => __('Russia', 'actify'),
		'Singapore' => __('Singapore', 'actify'),
		'Slovakia' => __('Slovakia', 'actify'),
		'Slovenia' => __('Slovenia', 'actify'),
		'South Africa' => __('South Africa', 'actify'),
		'Spain' => __('Spain', 'actify'),
		'Sweden' => __('Sweden', 'actify'),
		'Switzerland' => __('Switzerland', 'actify'),
		'Taiwan' => __('Taiwan', 'actify'),
		'Thailand' => __('Thailand', 'actify'),
		'Turkey' => __('Turkey', 'actify'),
		'Ukraine' => __('Ukraine', 'actify'),
		'United Kingdom' => __('United Kingdom', 'actify'),
		'United States (USA)' => __('United States (USA)', 'actify'),
		'Vietnam' => __('Vietnam', 'actify'),
		'Other: Europe' => __('Other: Europe', 'actify'),
		'Other: Americas' => __('Other: Americas', 'actify'),
		'Other: Asia' => __('Other: Asia', 'actify'),
	);
}
?>